### ISSUE TITLE
Finetune a classifier model

### ISSUE THREAD

**Issue by ndvbd** [up-33/extreme-fine-tuning#1]
Thank you for the lovely paper. In Algorithm 1, line 2, you add a FC layer to make the PTM a classifier. So, just to understand, the paper is for finetuning PTM as classifiers, right? Or is the algorithm able to finetune LMs as well?

**Comment by ShiragaP** [comment]
Thank you for your questions.

> So, just to understand, the paper is for finetuning PTM as classifiers, right? 
Yes. For this paper, the PTM is fine-tuned to be a classifier (with only fews epoch of BP). Then, a FC layer is replaced with an I-ELM based classifier.

> Or is the algorithm able to finetune LMs as well?
This paper is proposed for classification tasks, so it is up to the tasks to be applied.

**Comment by ShiragaP** [comment]
Thank you for your questions.

> So, just to understand, the paper is for finetuning PTM as classifiers, right? 

Yes. For this paper, the PTM is fine-tuned to be a classifier (with only fews epoch of BP). Then, a FC layer is replaced with an I-ELM based classifier.

> Or is the algorithm able to finetune LMs as well?

This paper is proposed for classification tasks, so it is up to the tasks to be applied. Classification tasks using LMs should work fine as well.
